In [1]:
import numpy as np

In [2]:
def shuffle_np_arrays(x, y):
    '''
    This only shuffle two numpy arrays along 0-dimension.
    Reference: https://tech.pic-collage.com/tips-of-numpy-shuffle-multiple-arrays-e4fb3e7ae2a
    '''
    # The dimension to shuffle is 0.
    dim_to_shuffle = 0
    # Generate the permutation index array.
    permutation = np.random.permutation(x.shape[dim_to_shuffle])
    # Shuffle the arrays by giving the permutation in the square brackets.
    shuffled_x = x[permutation]
    shuffled_y = y[permutation]
    return shuffled_x, shuffled_y

# How to use it

In [3]:
x = np.arange(12).reshape(4,3)
y = np.arange(4).reshape(4)

In [4]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
print(y)

[0 1 2 3]


In [6]:
shuffled_x, shuffled_y = shuffle_np_arrays(x, y)

In [7]:
print(shuffled_x)

[[ 0  1  2]
 [ 9 10 11]
 [ 3  4  5]
 [ 6  7  8]]


In [8]:
print(shuffled_y)

[0 3 1 2]
